### ISSUE TITLE
Not able to run example.py for translations

### ISSUE THREAD

**Issue by subnkve479** [AI4Bharat/IndicTrans2#32]
HI

I am not able to run example.py for translations.I am getting below error.I am able to port the checkpoint to HF.

(itv2_hf) venkata.kancherla@LM0004097 huggingface_inference % python3 example.py                        
Traceback (most recent call last):
  File "/Users/venkata.kancherla/Documents/My Projects/Indic Search queries/Translit_models/IndicTrans2/IndicTrans2/huggingface_inference/example.py", line 127, in <module>
    en_translations = batch_translate(
  File "/Users/venkata.kancherla/Documents/My Projects/Indic Search queries/Translit_models/IndicTrans2/IndicTrans2/huggingface_inference/example.py", line 76, in batch_translate
    generated_tokens = model.generate(
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/transformers/generation/utils.py", line 1593, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/transformers/generation/utils.py", line 742, in _prepare_encoder_decoder_kwargs_for_generation
    model_kwargs["encoder_outputs"]: ModelOutput = encoder(**encoder_kwargs)
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/venkata.kancherla/.cache/huggingface/modules/transformers_modules/ai4bharat/indictrans2-indic-en-1B/3cef3ffbd7fda581c930985163498f5ab8885121/modeling_indictrans.py", line 727, in forward
    layer_outputs = encoder_layer(
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/venkata.kancherla/.cache/huggingface/modules/transformers_modules/ai4bharat/indictrans2-indic-en-1B/3cef3ffbd7fda581c930985163498f5ab8885121/modeling_indictrans.py", line 381, in forward
    hidden_states = self.self_attn_layer_norm(hidden_states)
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/nn/modules/normalization.py", line 196, in forward
    return F.layer_norm(
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/nn/functional.py", line 2543, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
(itv2_hf) venkata.kancherla@LM0004097 huggingface_inference % python3 example.py
Traceback (most recent call last):
  File "/Users/venkata.kancherla/Documents/My Projects/Indic Search queries/Translit_models/IndicTrans2/IndicTrans2/huggingface_inference/example.py", line 127, in <module>
    en_translations = batch_translate(
  File "/Users/venkata.kancherla/Documents/My Projects/Indic Search queries/Translit_models/IndicTrans2/IndicTrans2/huggingface_inference/example.py", line 76, in batch_translate
    generated_tokens = model.generate(
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/transformers/generation/utils.py", line 1593, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/transformers/generation/utils.py", line 742, in _prepare_encoder_decoder_kwargs_for_generation
    model_kwargs["encoder_outputs"]: ModelOutput = encoder(**encoder_kwargs)
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/venkata.kancherla/.cache/huggingface/modules/transformers_modules/ai4bharat/indictrans2-indic-en-1B/3cef3ffbd7fda581c930985163498f5ab8885121/modeling_indictrans.py", line 727, in forward
    layer_outputs = encoder_layer(
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/venkata.kancherla/.cache/huggingface/modules/transformers_modules/ai4bharat/indictrans2-indic-en-1B/3cef3ffbd7fda581c930985163498f5ab8885121/modeling_indictrans.py", line 381, in forward
    hidden_states = self.self_attn_layer_norm(hidden_states)
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/nn/modules/normalization.py", line 196, in forward
    return F.layer_norm(
  File "/Users/venkata.kancherla/opt/anaconda3/envs/itv2_hf/lib/python3.9/site-packages/torch/nn/functional.py", line 2543, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

I see some posts to add --skip-torch-cuda-test.But I am not sure where to add this Can you please help

**Comment by jaygala24** [comment]
Hey

It seems that you're trying to execute `example.py` on the CPU instead of CUDA, and there is a simple modification required in the script to run it on the CPU. You need to comment out the highlighted line 45 ([link](https://github.com/AI4Bharat/IndicTrans2/blob/main/huggingface_inference/example.py#L45)) in the `example.py` script. Thank you!

**Comment by subnkve479** [comment]
Thanks a lot for quick reply.It is working!

**Comment by jaygala24** [comment]
Closing this issue as it seems to be resolved. Feel free to reopen the issue in case of any queries.
