### ISSUE TITLE
NameError: name 'postprocess_batch' is not defined

### ISSUE THREAD

**Issue by jerinphilip** [AI4Bharat/IndicTrans2#5]
Getting the following error from the library while trying to do a custom script translation on the ctranslate2 int8 model.

```pytb
$ python3 examples/ct2.py --ckpt-dir data/en-indic-deploy/ct2_int8_model/ --src-lang eng_Latn --tgt-lang mal_Mlym
Initializing sentencepiece model for SRC and TGT
Initializing model for translation
Hello world!
Traceback (most recent call last):
  File "/home/jerin/code/IndicTrans2/examples/ct2.py", line 24, in <module>
    model.batch_translate(sents, args.src_lang, args.tgt_lang)
  File "/home/jerin/code/IndicTrans2/inference/engine.py", line 248, in batch_translate
    return postprocess_batch(translations, tgt_lang, input_sents=batch)
    
NameError: name 'postprocess_batch' is not defined
```

Points to the following line:
https://github.com/AI4Bharat/IndicTrans2/blob/54efba3327e5ba5daab32f91d838402ab227263d/inference/engine.py#L248

The following fixes it for me.

```diff
diff --git a/inference/engine.py b/inference/engine.py
index 15bc21a..a63eefe 100644
--- a/inference/engine.py
+++ b/inference/engine.py
@@ -245,7 +245,7 @@ class Model:
 
         preprocessed_sents = self.preprocess_batch(batch, src_lang, tgt_lang)
         translations = self.translate_lines(preprocessed_sents)
-        return postprocess_batch(translations, tgt_lang, input_sents=batch)
+        return self.postprocess_batch(translations, tgt_lang, input_sents=batch)
     
     # translate a paragraph from src_lang to tgt_lang
     def translate_paragraph(self, paragraph: str, src_lang: str, tgt_lang: str) -> str:
```

**Comment by PranjalChitale** [comment]
Updated the script.
Thanks.
